#=============================================
#            AntiToolBoxTS
# @Theslowaja
# 1.0
# 4.0.0
#=============================================

kick-message: "ToolBox is not Allowed"

#=============================================